### ISSUE TITLE
How to Find A Key?

### ISSUE THREAD

**Issue by redmangospros** [herohamp/api-scratchtools#1]

**Comment by herohamp** [comment]
Oh, I guess it was not specific, the key is what you wanna see if the user posted

**Comment by redmangospros** [comment]
>How Do I Find A User key

**Comment by herohamp** [comment]
It's what ever you want, what ever you are searching if they posted

**Comment by redmangospros** [comment]
?

**Comment by DatOneLefty** [comment]
i believe it is the contents of the post, like for isOnline it is a 5 letter key that is a comment

**Comment by redmangospros** [comment]
Thanks! @DatOneLefty  and @herohamp

**Comment by herohamp** [comment]
Sorry, my explanation was bad, yes @DatOneLefty is correct

**Comment by redmangospros** [comment]
Thanks. ,,😂
